#lang scheme
(require "beanscheme.ss")

;;;;;;;TEST;;;;;;;;
(define HOST "localhost")
(define PORT 11300)
(define-values (in out) (open HOST PORT))

(list-tubes out in)
;(use "pepe" out in)
;(pause-tube "pepe" 10 out in)
;(peek-ready out in)
;(reserve out in)
;(bury 2 out in)
;(peek-delayed out in)
;(peek-buried out in)
;(list-tubes-watched out in)
;(list-tube-used out in)
;(put (make-bytes 5 65)  out in)
;(watch "jose" out in)
;(ignore "jose" out in)
;(touch 3 out in)
;(kick 3 out in)
;(display (stats-job 2 out in))
;(display (stats-tube "default" out in))
;(display (stats out in))
;(release 2 out in)
;(bury 3 out in)
;(delete 4 out in)
(quit out in)